
management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
      domain: spring.demo
  endpoint:
    health:
      show-details: always
      enabled: true
    mappings:
      enabled: true
  info:
    git:
      mode: full
spring:
  redis:
    host: 192.168.117.60
info:
  app:
    encoding: UTF-8
    source: 1.8.0_51